version: '2'
services: 
  prestashop:
    build: ./docker/prestashop
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./docker/common:/scripts
      - ./src:/var/www/html
      - ./src/modules:/var/www/html/modules
      - ./src/themes:/var/www/html/themes
      - ./src/override:/var/www/html/override
      - ./docker/apache2/certs:/ssl/certs
      - ./docker/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/apache2/sites-available:/etc/apache2/sites-available
    environment:
      - PS_DEV_MODE=0
      - PS_INSTALL_AUTO=0
    logging:
     options:
      max-size: 2G
  phpmyadmin:
    build: ./docker/phpmyadmin
    ports: 
      - 8336:443 
    environment:
      - PMA_HOST=10.0.0.0
    restart: always
    volumes:
     - ./docker/phpmyadmin:/etc/phpmyadmin
     - ./docker/phpmyadmin/theme:/www/themes/theme
     - ./docker/apache2/certs:/ssl/certs
     - ./docker/apache2/sites-enabled:/etc/apache2/sites-enabled
     - ./docker/apache2/sites-available:/etc/apache2/sites-available
    logging:
      options:
        max-size: 500M
